version: '3.8'

services:
  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tools-index-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - tools-index-network

  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tools-index-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    networks:
      - tools-index-network

  # MongoDB数据库
  mongo:
    image: mongo:latest
    container_name: tools-index-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - tools-index-network

  # Nginx代理服务
  nginx:
    image: nginx:alpine
    container_name: tools-index-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - tools-index-network

# 网络配置
networks:
  tools-index-network:
    driver: bridge

# 数据卷配置
volumes:
  mongo-data:
